- rtv/main.py
Previously, your password is both visible on the command line as you type it as well as stored in your terminal history. This will prompt the user for their password using Python's built-in getpass module, which will keep it far more secure.
> changed password to a getpass prompt for all sorts of security reasons

- README.rst
- rtv/subreddit.py
This will allow you to open non-self posts in a browser. It will default to opening a new browser in an existing window, or open a new window of the default browser if you do not currently have a browser open. the keystroke is 'o' which fits really nicely for key bindings and makes sense as the word 'open'.
> Added functionality to open the submission link in the browser.

- rtv/curses_helpers.py
I updated an import changing `docs.HELP.split('\n')` to `HELP.split('\n')` now shows help appropriately.
> Pressing '?' crashes the client

- MANIFEST.in
Otherwise, version.py would not be included by `setup.py sdist`, making
the package on PyPi unusable.
> Add version.py to MANIFEST.in

- rtv/content.py
We were comparing the name to the author which was never true. This was causing the author's name to never be highlighted green in the comments.
Fixed so `data['is_author']` is now correct.
> fixed bug for author highlighting in comments

- rtv/__main__.py
Displays the name and version in the terminal title. Nothing too fancy, just helps when you have 5 terminals open :D
Tested on linux. The first method works for linux and OSX. The second should work for Windows..
> added program title to terminal title

- README.rst
- rtv/__main__.py
Config file is read from the first of these two locations:
* $XDG_CONFIG_HOME/rtv/rtv.cfg
* ~/.rtv
> Read config from XDG_CONFIG_HOME (Fix #65)

- rtv/submission.py
- rtv/subreddit.py
praw could return None for \*flair\* params, don't show this.
Thats's what I saw before this fix:
and
> Don't show flair when it's None

- README.rst
- rtv/docs.py
- rtv/oauth.py
- rtv/page.py
- setup.py
Hey, I finished implementing terminal web browser support. It was much easier with ``curses.endwin()`` and ``curses.doupdate()``. I had looked Python Curses documentation, but I guess I couldn't figure ``curses.doupdate()`` would set screen back up, maybe because the documentation was not very explicit about it. Anyway, it is working now, and much cleaner than my previous attempt. :)
> OAuth terminal web browser support

- rtv/content.py
Any SUBREDDIT with special characters like u'\xe3' are triggering an error at line 141, data['flair'] = '[{}]'.format(data['flair'].strip()) .
The solution was to add u'[{}]' to the concatenation.
The original error message: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 7: ordinal not in range(128) .
> After update to version 1.6.1 Exception UnicodeEncodeError closes the application

- rtv/terminal.py
> Use communicate() to avoid subprocess hanging.

- rtv/config.py
- rtv/content.py
- rtv/submission_page.py
- rtv/subreddit_page.py
- rtv/templates/rtv.cfg
I opened a feature request issue for this but decided to implement it.
I've added a command line and config file argument for to set the maximum column width for submission comments. By default this is set to 80.
This makes reading comments much smoother when using a full screen terminal.
It's only my second contribution to someone else's code, so feedback on code quality is welcome :)
> Setting the maximum comment column width

- rtv/config.py
- rtv/page.py
- rtv/templates/rtv.cfg
Close #306 if merged.
A new option in the config file to hide your username if you're logged in, and display "Logged in" instead.
Local tests are passing.
Also updated the template config.
> Option to hide the username if logged in

- rtv/docs.py
'j' is actually down, and 'k' is up.
> Correct docs.py

- rtv/page.py
- rtv/terminal.py
School is over so I finally got around to this. The clear_screen() method in the Terminal class checks the $TERM variable in an attempt to avoid both the tmux and urxvt bugs. I was unable to test with tmux but it removes the flashing using urxvt.
> Issue #343 Added method to clear screen

- rtv/mime_parsers.py
- tests/test_mime_parsers.py
Entire imgur albums can be downloaded rather than the max 10 images from scraping the webpage.
There is a rate limit on the number of request. I'm not sure if there are enough users of `rtv` to run into any trouble.
> Use imgur api to retrieve direct links to images.

- .travis.yml
- tests/test_terminal.py
On Ubuntu 14.04, ``webbrowser._tryorder`` was returning ``["www.browser", "w3m"]``. This was causing a failure in a test that was trying to spoof the darwin platform. The solution was to mock out  ``_tryorder`` in order to have better control over the environment.
> Fix travis

- rtv/submission_page.py
Per #415, add '[S]' to the end of the submitter's username on their own comments.
> RE #415: Add '[S]' to submitter username on comments

- rtv/__main__.py
- rtv/config.py
- rtv/oauth.py
- rtv/objects.py
- rtv/page.py
- rtv/submission_page.py
- rtv/subreddit_page.py
- rtv/subscription_page.py
- rtv/terminal.py
- rtv/theme.py
- tests/conftest.py
- tests/test_objects.py
- tests/test_submission.py
- tests/test_subreddit.py
- tests/test_subscription.py
- tests/test_terminal.py
This PR contains some code cleanup and refactoring with the intention of making it easier to add support for custom themes later. Most of this has been cherry-picked from my other themes branch. I want to get some of the non-breaking changes into master now to minimize the overall diff and chance of breaking things.
Changes include:
- Replacing the ``Color`` class with a more flexible ``Theme`` class. The ``Theme`` class is still a stub for now and will be filled out later.
- Moving all color and text modifier definitions to a central dictionary.
- Adding an optional ``style`` parameter to ``term.show_notification``. For now all of the styles (info, loading, warning, error) are displayed the same way so this has no effect. In the future, error messages might be colored differently …
> preparing for themes

- rtv/templates/mailcap
I simplified the mailcap entry for youtube videos using mpv. No need to pipe the stream from youtube-dl into mpv anymore since this latter can directly handle youtube urls. Bonus side effect : it's now possible to navigate backward and forward in the video.
> Youtube videos are now directly handled by mpv in mailcap

- rtv/templates/mailcap
Gifs were previously handled by feh which can only display the first frame.
> Changed gif handler to mpv and removed redundant webm entry in mailcap

- .travis.yml
- setup.py
I'm going to follow suit from pytest and drop support for python 3.3.
https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#deprecations-and-removals
For python 3.3 users (are there any out there?), rtv will still be installable through pip but the test suite will no longer be run.
> Drop python 3.3 support

- rtv/config.py
- rtv/templates/rtv.cfg
- rtv/terminal.py
- tests/test_config.py
- tests/test_terminal.py
This pull request adds the option to disable screen flashing entirely. Also includes tests and everything else needed for a new rtv option.
Ref: #478
> Add --no-flash option to rtv

- rtv/terminal.py
Fixes https://github.com/michael-lazar/rtv/issues/534
> Catch unexpected null-byte errors when adding strings to curses

- rtv/themes/colorblind-dark.cfg
Added basic dark colorblind theme requested in #547. The colors were chosen using the guidelines seen in: 
[Tips + Tricks with Beamer for Economists](https://paulgp.github.io/beamer_tips.pdf) (PDF file page 10/40).
> Add dark colorblind theme

- rtv/__main__.py
- rtv/terminal.py
Reddit submissions and comments are styled with Markdown.  If you have a
Markdown-aware pager/viewer on your system it is convenient to be able to
use it rather than the default 'less'/'more'/etc. one used for everything
else on the system.  Support a high-priority environment variable that
will be consulted prior to checking $PAGER and/or defaulting to 'less'.
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>
> pager: Add RTV_PAGER to support a reddit-specific setting

- rtv/__main__.py
- rtv/config.py
- rtv/templates/rtv.cfg
This PR introduces the `--no-autologin` cli parameter and the correlating `autologin` config option. A user could be willing to skip automatic login, to speed up the startup of rtv.
> Issue #597: Autologin configuration

- rtv/content.py
```
Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/user/builds/rtv/rtv/__main__.py", line 252, in <module>
sys.exit(main())
File "/home/user/builds/rtv/rtv/__main__.py", line 231, in main
page.open_submission(url=url)
File "/home/user/builds/rtv/rtv/subreddit_page.py", line 186, in open_submission
page.loop()
File "/home/user/builds/rtv/rtv/page.py", line 84, in loop
self.controller.trigger(ch)
File "/home/user/builds/rtv/rtv/objects.py", line 604, in trigger
return func(self.instance, *args, **kwargs)
File "/home/user/builds/rtv/rtv/submission_page.py", line 148, in open_link
opened_link = …
```
> Fix crash in extract_links when self text is blank

- rtv/templates/mailcap
The default mailcap for rtv is nice with some presets for viewing images in iTerm2, but it expects that paths are URLs. Other apps that use mailcap, such as mutt/neomutt, provide paths on the filesystem instead of URLs.
This PR modifies the mailcap template to check if the provided path starts with http, and uses curl to fetch the image only if the path starts with http. Otherwise, it directly pushes it to iterm2's imgcat. This makes it possible for mutt and rtv to share the same mailcap.
> Mailcap: support URLs and files

- rtv/terminal.py
Lines beginning with four space are treated as code on reddit.
`rtv` strips leading whitespace before sending posts to reddit thus preventing code blocks from being recoginzed.
This fix should strip only leading empty lines rather than all leading whitespace.
> Improve comment formatting for markdown code block

- rtv/config.py
- rtv/submission_page.py
- rtv/templates/rtv.cfg
Some times I find it easier to read the text when it's wrapped to 70 columns. So I've added an option to set the maximum width (disabled by default) for the pager.
> Add max column width for pager

- rtv/page.py
Handles #640 
I wasn't able to reproduce the reported error, but this should prevent the app from crashing.
> Fix edge-case when printing terminal title

- rtv/terminal.py
- tests/test_terminal.py
Fixes regression described in #649
> Prevent stripping newlines in the middle of markdown submissions

- rtv/templates/mailcap
This is a real small PR for the mailcap template, but it's something I was missing when viewing images.
```bash
-., --scale-down                                                                                                                                                                                            
Scale images to fit window geometry (defaults to screen size when no geometry was specified).
Note that the window geometry is not updated when changing images at the moment.
This option is recommended for tiling window managers.  This option is ignored when in 
fullscreen and thumbnail list mode. 
In tiling environments, this also causes the image to be centered in the window.
```
> Make sure feh scales the image to fit the window

- rtv/config.py
- rtv/templates/rtv.cfg
- rtv/terminal.py
#669 
Added an option to the config file, _force_new_browser_window_, which when set opens links 
in a a new window instead of a new tab in the running browser. 
[Note] Option works with old config files. If the config file doesn't have this option defined the old behavior (open in new tab) will be performed.
> Add option to force opening links in new browser window
