rtv/content.py

Sort of screwed up the commits because I've never actually contributed to a project before. Oh well, first time. Anyways, I added the /top and /new functionality. All I really did was check if '/' is present, and parse it if its there.

/top and /new

---

rtv/content.py

Preserve newlines in comments and posts

---

rtv/content.py

Realized this was an easy thing to add. Just allows the user to do /r/new and bring up the front page's new.

Added option to got to front page /new

---

rtv/content.py

Once again for issue: https://github.com/michael-lazar/rtv/issues/17
Fixes everything in issue except for the multireddits.
As far as I can tell there are no more errors dealing with backslashes that won't be caught. Couldn't come up with anything anyways.
Also makes front into a sort of alias (where front/new goes to new)

A fix for the backslash bugs (plus front/... alias)

---

rtv/main.py

Fix bug with login where invalid password throws unhandeled exception in

---

rtv/main.py
rtv/submission.py
rtv/subreddit.py
rtv/utils.py

Help message command added.
Hit `?` and the help message box appears.

help message command added

---

__main__.py
rtv/content.py
rtv/main.py

Set utf-8 by default, if -a flag is used, then ascii is used instead.

Fixed issue #23

---

rtv/submission.py
rtv/utils.py

Press c to add a comment on the submission if a header is selected, or reply to a comment if the comment is selected.
Due to curses bug, textbox can only work on overwrite mode (insert mode not working).
p.s. Ignore the last pull request. I combined all the commits.

add_comment function added

---

setup.py

Trying to setup a dev environment, and ran into some issues.

Fix setup.py from throwing errors

---

rtv/curses_helpers.py

More leftovers from the refactoring?

Fix EscapeInterrupt not being defined.

---

README.rst
rtv/utils.py

Help for comment/reply function added

---

rtv/docs.py
rtv/submission.py

Instead of pasting together your own curses textbox will all the bells and whistles that you need,
why not use what's already there?

Use EDITOR to write comments and replies.

---

README.rst
rtv/docs.py
rtv/page.py
rtv/submission.py
rtv/subreddit.py

Ported code from the stale controller branch.
Eliminates the large while loop with nested if statements by creating a Controller class for each page that registers functions with each input command.
In addition, I added a keybinding to the `ENTER` key to open links. This make it easier for users who are navigating using the arrow keys.

Command Controllers and Command decorators

---

README.rst
rtv/content.py
rtv/docs.py
rtv/page.py
rtv/subreddit.py

I implemented searching of a subreddit using praw's search function. Simply type `f` to open the search prompt. If no results were found, there is a popup message.
Also moved prompt_input to it's own method in the BasePage so it can be used for future prompts.
#39

Subreddit Search implemented

---

rtv/curses_helpers.py
rtv/docs.py
rtv/page.py

I don't think we have to change any data structures after logging in.

Login with `u` key

---

rtv/content.py
rtv/curses_helpers.py
rtv/submission.py

Places Yellow ✪ in comment heading of gilded comments. Resolves #57 
Example: 
```
rtv -l http://www.reddit.com/r/pics/comments/317w6v/mom_posted_pic_of_doll_she_made_nice_job_mom_wait/cpzmfbd
```

added gold symbol next to gilded comments

---

rtv/docs.py
rtv/subreddit.py

Reused a bit of the code from commenting.
The only issue is the page refresh. I think the submit method is taking longer so it's not refreshing the content correctly. Maybe we could make another loader to run until the submission is done?
Also, probably save this for next version, 1.2 perhaps.

Added posting a Submission (text post)

---

rtv/content.py
rtv/curses_helpers.py
rtv/submission.py
rtv/subreddit.py

Now everything is gilded!
(I'm not sure if I gitted 100% corectly, but I fixed the conflicts so it can be merged)

Added gold to submissions

---

rtv/docs.py
rtv/page.py
rtv/subreddit.py

A lot of this logic was basically the same for submissions and comments, so I decided to put it in the BasePage. 
I cherry picked some code from #66 Thanks to @yskmt

Edit/Delete Submissions and Comments

---

rtv/submission.py

Quick fix to resolve #90 
Adds the upvote/downvote symbol to the submission view.

added upvote/downvote to submission view

---

rtv/page.py

To address issue https://github.com/michael-lazar/rtv/issues/27
`m` and `n` keys to page up and down. 
It is implemented for both submission and subreddit mode, but I think it is more useful to browse submissions in subreddit mode.

page up/down implemented

---

rtv/history.py
rtv/subreddit.py

How this works
1. Load the contents of the history file into a set
2. As a link is visited, add it to the set
3. On exit (crtl+c or q), write a max of 200 elements of the set to the file

History Log across multiple sessions

---

rtv/content.py
rtv/curses_helpers.py
rtv/helpers.py
rtv/history.py
rtv/page.py
rtv/submission.py
rtv/subreddit.py

A few very minor style changes to adhere more closely to PEP8.

Minor PEP8 corrections

---

rtv/page.py

Addresses Issue #109
Also two small PEP8 changes.

added the ability to check for unread messages with the 'i' key

---

rtv/helpers.py
rtv/page.py
rtv/submission.py
rtv/subreddit.py

Code cleanup

---

rtv/subreddit.py

Simple fix to open the comments section instead of the browser on selfposts
Resolves #121

opens selfposts internally instead of in the browser

---

rtv/content.py
rtv/subreddit.py

Thought it made sense to handle crossposts internally too. generally improved the determination of what is a self/cross post.

Handle internal reddit links internally, including x-posts

---

rtv/content.py
rtv/submission.py
rtv/subreddit.py

I think it is related to:
https://github.com/michael-lazar/rtv/pull/11 and https://github.com/michael-lazar/rtv/pull/13
Keys:
1: hot, 2: top, 3: rising, 4: new, 5: controversial
The header shows the sorting method next to title
I also added `praw.errors.NotFound` in `SubredditContent.__init__` so this issue https://github.com/michael-lazar/rtv/issues/80 should be fixed too.

Number keys to refresh the submission/comments and sort by hot/top/rising/new/controversial

---

.gitignore
rtv/content.py
rtv/subreddit.py

add the intermediate setuptools files to the .gitignore and use the subreddit field from the PRAW Submission object instead of getting it out of the URL.

Just a couple of little things

---

rtv/subreddit.py

Links for selfposts and x-posts don't go purple after my last PR (#126). This'll fix it.

Don't forget to add selfposts and x-posts to history

---

README.rst
rtv/__main__.py
rtv/content.py
rtv/curses_helpers.py
rtv/docs.py
rtv/exceptions.py
rtv/page.py
rtv/subreddit.py
rtv/subscriptions.py

Added the ability for authenticated users to view their subscribed subreddits, and to jump to one of them.

Adding "subscriptions" feature

---

README.rst
rtv/__main__.py
rtv/oauth.py
rtv/page.py
rtv/submission.py
rtv/subreddit.py
rtv/subscription.py

This pull request is here to adress issues with OAuth

OAuth improvements and bugfixes

---

MANIFEST.in
rtv.1
setup.py

Added a simple man page, if this is a shit idea. Or you'd like something re-done let me know. 
Most of it is taken from -h output, be glad to redo any bit.

added a manpage

---

rtv/content.py
rtv/oauth.py
rtv/page.py

Logout and quit prompts and other small stuff.

---

README.rst
rtv/__main__.py
rtv/config.py
rtv/content.py
rtv/helpers.py
rtv/history.py
rtv/oauth.py
rtv/page.py
rtv/subreddit.py
rtv/subscription.py

Few aesthetic changes so the code is completely linted. 
Also updated the screenshot to match the new features -- specially the post count -- and the pypi badge (it works under 3.5 without a hitch).

New screenshot and code width

---

README.rst
rtv/docs.py
rtv/page.py
rtv/subscription.py

As asked by @shaggytwodope on #156, and fixes #161.

Force quit and subscription page fixes

---

README.rst

For issue #159, might not be what you had in mind. But I think it covers what folks should know.

pip3 info in readme for issue #159

---

rtv/content.py

Support hidden scores

---

rtv/content.py
rtv/submission.py
rtv/subreddit.py
rtv/terminal.py

Add coloured tag for sticky comments.

---

rtv/subreddit.py
rtv/terminal.py

Add space between timestamp and comment count

---

setup.py

Force praw 3 version

---

rtv/content.py
tests/test_content.py

Fix bug where submission indicies were duplicated when paging. #209

---

rtv/__main__.py

Flush sys.stdout after writing the title.

---

rtv/content.py
tests/test_content.py

Check for empty subreddit name.

---

rtv/__main__.py
rtv/page.py
rtv/terminal.py
tests/test_terminal.py

Fixes https://github.com/michael-lazar/rtv/issues/246

Don't set title when no DISPLAY

---

tests/conftest.py
tests/test_submission.py
tests/test_subscription.py

Disable unit tests from deleting refresh token.

---

rtv/mime_parsers.py

Example pages:
`https://instagram.com/p/3Whn5uL5UF/?taken-by=paavideos`
`https://www.instagram.com/p/BFez8VLgGTM/?hl=en`

Add instagram parser

---

rtv/__main__.py
rtv/objects.py

Expand URLs.

---

.travis.yml
rtv/__main__.py
rtv/config.py
rtv/docs.py
rtv/oauth.py
rtv/templates/index.html
rtv/terminal.py
setup.cfg
setup.py
tests/cassettes/test_subreddit_open_multireddits.yaml
tests/conftest.py
tests/test_config.py
tests/test_content.py
tests/test_oauth.py
tests/test_objects.py
tests/test_submission.py
tests/test_subreddit.py
tests/test_terminal.py

Addresses the following issues
https://github.com/michael-lazar/rtv/issues/211
https://github.com/michael-lazar/rtv/issues/271

Remove tornado

---

rtv/docs.py
rtv/page.py
rtv/submission.py
rtv/subreddit.py
rtv/subscription.py
rtv/terminal.py
tests/test_submission.py
tests/test_terminal.py

Help footer

---

rtv/__main__.py
rtv/page.py

Unset locale

---

rtv/terminal.py

Secure urls before sending to Popen.

---

rtv/docs.py
rtv/page.py

in reference to issue #308 
Causes odd behavior in `/r/front` subreddit so disabled in that context.

Added 'links from' menu

---

rtv/content.py
rtv/exceptions.py
rtv/objects.py
tests/test_content.py

Addresses https://github.com/michael-lazar/rtv/issues/251

Better error messages

---

README.rst

AUR package in working order

---

rtv/terminal.py

Fix for using Popen without shell=true for multi-part commands

---

setup.cfg
setup.py

Upping requests version

---

.pylintrc
requirements.txt
rtv/__main__.py
rtv/content.py
rtv/objects.py
rtv/packages/__init__.py
rtv/packages/praw/__init__.py
rtv/packages/praw/decorator_helpers.py
rtv/packages/praw/decorators.py
rtv/packages/praw/errors.py
rtv/packages/praw/handlers.py
rtv/packages/praw/helpers.py
rtv/packages/praw/internal.py
rtv/packages/praw/multiprocess.py
rtv/packages/praw/objects.py
rtv/packages/praw/praw.ini
rtv/packages/praw/settings.py
rtv/page.py
rtv/terminal.py
scripts/update_packages.py
setup.cfg
setup.py
tests/conftest.py
tests/test_content.py
tests/test_oauth.py
tests/test_packages.py
tests/test_submission.py
tests/test_subreddit.py
tests/test_subscription.py
tests/test_terminal.py

This adds a bundled version of praw v3 inside of the rtv package

Bundled praw

---

rtv/__main__.py

Added a try-catch for invalid locales on osx

---

README.rst

Sprucing up the README, wanted to test it out before committing to master

Messing with readme

---

rtv/submission_page.py

Allow opening of submission link from the comments page with the `o` key

---

rtv/__main__.py

Catch the exception if curses cant be imported

---

rtv/content.py

Fix issue #369 
Also, can now see both comments and submissions on user pages.

Load comments

---

rtv/exceptions.py
rtv/oauth.py
tests/cassettes/test_oauth_authorize_invalid_token.yaml
tests/cassettes/test_oauth_authorize_with_refresh_token.yaml
tests/test_oauth.py

This addresses #366 by automatically deleting the refresh-token if the server returns a 400 error.

Corrupt access token

---

rtv/templates/mailcap

Tiny typo correction in the mailcap template file.
Corresponding issue: #380

Mailcap template typo correction

---

rtv/content.py
rtv/page.py
rtv/submission_page.py
rtv/subreddit_page.py
rtv/subscription_page.py
tests/test_page.py

Search sorting

---

rtv/objects.py
tests/test_config.py
tests/test_objects.py

set_bindings can now update or replace existing bindings

---

rtv/templates/mailcap

Fixes https://github.com/michael-lazar/rtv/issues/390 and https://github.com/michael-lazar/rtv/issues/385

Updating mailcap examples for framebuffer videos and iTerm2 imgcat

---

.gitignore
.travis.yml
README.rst
rtv/__main__.py
rtv/terminal.py

Addresses issue https://github.com/michael-lazar/rtv/issues/403

Add $VISUAL

---

rtv/mime_parsers.py
tests/cassettes/test_parser[reddit_gif].yaml
tests/cassettes/test_parser[reddit_video].yaml
tests/test_mime_parsers.py

mime parser for reddit hosted video

---

rtv/submission_page.py
rtv/subreddit_page.py
rtv/subscription_page.py
tests/cassettes/test_submission_prompt_submission[prompt_1].yaml
tests/cassettes/test_submission_prompt_submission[prompt_2].yaml
tests/cassettes/test_submission_prompt_submission[prompt_3].yaml
tests/cassettes/test_submission_prompt_submission[prompt_4].yaml
tests/cassettes/test_submission_prompt_submission[prompt_5].yaml
tests/test_submission.py

Fixes outstanding issue in https://github.com/michael-lazar/rtv/issues/294

Allow navigating to comments from the prompt on the submission page

---

rtv/content.py
tests/cassettes/test_content_subreddit_from_name_authenticated[me-multi].yaml
tests/test_content.py

Support /u/me/m/multireddit from prompt

---

rtv/__main__.py
rtv/mime_parsers.py
rtv/objects.py
rtv/terminal.py
scripts/inspect_webbrowser.py
tests/test_mime_parsers.py
tests/test_objects.py
tests/test_terminal.py

This addresses the following issues:
https://github.com/michael-lazar/rtv/issues/420
https://github.com/michael-lazar/rtv/issues/414

Rtv browser

---

rtv/page.py

Changing logout prompt to a pop-up notification

---

rtv/terminal.py

Fix crash when submission page contains non standard characters

---

rtv/mime_parsers.py
tests/cassettes/test_imgur_fallback.yaml
tests/cassettes/test_parser[imgur_album].yaml
tests/test_mime_parsers.py

Imgur galleries containing only a single animated image were not being parsed properly causing a crash.
example: https://imgur.com/gallery/vLHI7

handle single image imgur galleries

---

README.md

Signed-off-by: Vivek Anand <vivekanand1101@gmail.com>

Readme: it's dnf not yum for fedora 24+

---

README.md

Added method using Nix package manager

Added additional installation way

---

rtv/objects.py
rtv/terminal.py
tests/test_terminal.py

Fix crash on startup when terminal doesn't support colors

---

rtv/page.py
tests/test_subreddit.py
tests/test_terminal.py

Adding support for emacs terminals

---

requirements.txt
rtv/terminal.py

https://github.com/michael-lazar/rtv/issues/463

Surpressing stdout/stderr from opening web browsers

---

rtv/submission_page.py
rtv/terminal.py

Wrap text in submission page PAGER output

---

rtv/objects.py

Fixes issue https://github.com/michael-lazar/rtv/issues/471

Adding surf to the list of default webbrowsers

---

rtv/objects.py

Fixes https://github.com/michael-lazar/rtv/issues/476

Fixing the command for the opera webbrowser

---

rtv/subreddit_page.py
rtv/theme.py
rtv/themes/default.cfg.example
rtv/themes/molokai.cfg
rtv/themes/papercolor.cfg
rtv/themes/solarized-dark.cfg
rtv/themes/solarized-light.cfg

Un-bolding the text title for seen submissions

---

rtv/templates/rtv.cfg

Fix theme name in a sample config file

Fix theme name in a sample config file

---

rtv/oauth.py
tests/conftest.py
tests/test_oauth.py

Fixes issue https://github.com/michael-lazar/rtv/issues/521

Sending OAuth Server errors to the log instead of printing to stdout

---

rtv/packages/__init__.py
rtv/packages/praw/errors.py

Fixes https://github.com/michael-lazar/rtv/issues/499

Pulling in changes from praw repo

---

rtv/terminal.py

Fixes https://github.com/michael-lazar/rtv/issues/530

Fixing invalid null byte handling for python 2

---

rtv/objects.py

Fixes https://github.com/michael-lazar/rtv/issues/546

Add support for qutebrowser

---

rtv/templates/mailcap

fix video/x-youtube to work with v.redd.it links

---

rtv/mime_parsers.py
tests/test_mime_parsers.py

Add mime parser: vimeo.com

---

rtv/docs.py
rtv/page.py
rtv/submission_page.py
rtv/terminal.py
tests/test_terminal.py

Implements https://github.com/michael-lazar/rtv/issues/557

Changed the help text format when editing comments & submissions

---

rtv/docs.py
tests/test_submission.py

This PR adds the "refresh" shortcut to the footer. See [issue 585](https://github.com/michael-lazar/rtv/issues/585).

Adds refresh to footer

---

rtv/content.py
rtv/submission_page.py
rtv/terminal.py

Give the user the ability to open links, that are mentioned in comments and submissions.
If there are links mentioned in a comment or submission's text the user will be prompted to select the link he/she wants to open, when pressing ENTER (default key bindings).
Links to a page within reddit are currently not opened within rtv. I think it's debatable whether that's the expected behavior or not.
I will appreciate any feedback :-)
@QA: Here are some links for testing different behaviors:
"Link only submissions" still open the link: https://www.reddit.com/r/unixporn/comments/8uq1ti/bspwm_daft_punk/
Submissions with text still open the permalink: https://www.reddit.com/r/AMA/comments/8e19nw/i_am_the_voice_of_boo_from_monsters_inc_ama/
Submissions with text, that mentions links open prompt: …

Issue #593: Allow opening links

---

rtv/content.py
rtv/submission_page.py
rtv/subreddit_page.py

Indicate edited submissions/comments.

---

rtv/__main__.py

Load links from the command line before loading the subreddit

---

CHANGELOG.rst
rtv/__main__.py
rtv/config.py

Improve traceback

---

CONTROLS.md
rtv/docs.py

Fixed small typo in help page regarding vim style movement
Issue: #680

Fixed small typo
